num_epochs: 20
num_workers: 2
batch_size: 2
input_size: 224




opt:
    opt: "SGD"
    lr: 0.005
    weight_decay: 0.0005
    momentum: 0.9
    step_size: 3
    gamma: 0.1

aug:
    interpolation: "bilinear"
    fill_color: "mean"
