name: lint

on:
    push:
        branches:
            - master

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.7"

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
        - name: Lint
          run: |
            flake8 . --max-line-length=120 --max-complexity=10 --ignore=F405,F403,C901 --show-source --statistics
            black . --check
            isort .  --profile black --check-only
            bandit .
