name: tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest tests/ #add cov later
